# Generated by Django 5.0.3 on 2024-06-19 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0002_narrative_topic_topstories_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='title',
            new_name='topic',
        ),
    ]
