# Generated by Django 5.0.3 on 2024-06-20 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0003_rename_title_topic_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='narrative',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
