# Generated by Django 5.0.3 on 2024-06-20 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0007_topstories_narrative'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentimentanalysis',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sentiments', to='sentiment.topic'),
        ),
        migrations.AddField(
            model_name='topstories',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='sentiment.topic'),
        ),
    ]
