# Generated by Django 5.0.3 on 2024-07-09 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0008_sentimentanalysis_topic_topstories_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topstories',
            name='impact_score',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='topstories',
            name='publisher_level',
            field=models.IntegerField(default=-1),
        ),
    ]
